CREATE TABLE hotels (
	hotel VARCHAR(255),
    is_canceled BOOL,
    lead_time INT(10),
    arrival_date_year INT(10),
    arrival_date_month VARCHAR(255),
    arrival_date_week_number INT(10),
    arrival_date_day_of_month INT(10),
    stays_in_weekend_nights INT(10),
    stays_in_week_nights INT(10),
    adults INT(10),
    children INT(10),
    babies INT(10),
    meal VARCHAR(255),
    country VARCHAR(255),
    market_segment VARCHAR(255),
    distribution_channel VARCHAR(255),
    is_repeated_guest BOOL,
    previous_cancellations INT(10),
    previous_bookings_not_canceled INT(10),
	reserved_room_type VARCHAR(255),
    assigned_room_type VARCHAR(255),
    booking_changes INT(10),
    deposit_type VARCHAR(255),
    agent VARCHAR(255),
	company VARCHAR(255),
    days_in_waiting_list INT(10),
    customer_type VARCHAR(255),
    adr DEC(10, 2),
    required_car_parking_spaces INT(10),
    total_of_special_requests INT(10),
    reservation_status VARCHAR(255),
    reservation_status_date DATE
);